# Generated by Django 4.1.1 on 2022-09-24 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0002_rename_items_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vending_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vending_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventories.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventories.vending_location')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventories.item')),
            ],
        ),
        migrations.CreateModel(
            name='Needed_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventories.item')),
            ],
        ),
    ]
