# Generated by Django 4.1.1 on 2022-09-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0003_vending_location_vending_inventory_purchase_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needed_inventory',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventories.item'),
        ),
    ]
