# Generated by Django 4.1.1 on 2022-09-24 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0005_alter_needed_inventory_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needed_inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neededinvs', to='Inventories.item'),
        ),
    ]
