# Generated by Django 4.1.1 on 2022-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0007_alter_needed_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='needed_inventory',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='needed_inventory',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
