# Generated by Django 4.1.1 on 2022-09-25 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0010_alter_needed_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_history',
            name='purchase_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
