# Generated by Django 4.1.1 on 2022-09-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0011_alter_purchase_history_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needed_inventory',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Inventories.item'),
        ),
    ]
