# Generated by Django 4.1.1 on 2022-09-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0012_alter_needed_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.URLField(default=None, null=True),
        ),
    ]
