# Generated by Django 4.1.1 on 2022-09-30 01:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0013_item_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocking_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_date', models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 30, 1, 17, 37, 358265, tzinfo=datetime.timezone.utc))),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventories.vending_location')),
            ],
        ),
    ]
