# Generated by Django 4.1.1 on 2022-09-30 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0014_stocking_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocking_history',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 30, 1, 22, 21, 59728, tzinfo=datetime.timezone.utc)),
        ),
    ]
