# Generated by Django 4.1.1 on 2022-10-22 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0015_alter_stocking_history_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needed_inventory',
            name='admin_approved',
        ),
        migrations.RemoveField(
            model_name='needed_inventory',
            name='purchased',
        ),
        migrations.AlterField(
            model_name='stocking_history',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 22, 15, 51, 25, 574206, tzinfo=datetime.timezone.utc)),
        ),
    ]
