# Generated by Django 4.1.1 on 2022-11-07 13:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0016_remove_needed_inventory_admin_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daterange', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='needed_inventory',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stocking_history',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 7, 13, 32, 6, 407187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='IncomeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('transactions', models.IntegerField()),
                ('net_amnt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daterange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventories.incomemaster')),
            ],
        ),
    ]
