# Generated by Django 4.1.1 on 2022-11-12 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0018_incomedetail_type_alter_stocking_history_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomedetail',
            name='type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stocking_history',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 14, 48, 56, 912301, tzinfo=datetime.timezone.utc)),
        ),
    ]
