# Generated by Django 4.1.1 on 2022-11-29 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0020_alter_incomedetail_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocking_history',
            name='stock_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 13, 24, 56, 380413, tzinfo=datetime.timezone.utc)),
        ),
    ]
