# Generated by Django 4.1.1 on 2023-01-26 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventories', '0026_alter_stocking_history_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocking_history',
            name='stock_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
